# Generated by Django 6.0.2 on 2026-04-17 18:41

import leads.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_user_options_alter_user_managers_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', leads.models.UserManager()),
            ],
        ),
    ]
