# Generated by Copilot on 2026-05-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_calendarevent_recurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='color',
        ),
    ]
